unit PrjConst;

interface

resourcestring
  SDEMANDERS = 'D E M A N D E R S';
  SDEMANDERS1 = 'D E M A N D E R S  (Active)';
  SDEMANDERS2 = 'D E M A N D E R S  (InActive)';
  SName_str = 'Name_str';
  SDeleteStaffMember = 'Delete Staff member?';
  SAddAllItemsFromI = 'Add all Items from Institutional EDL?';
  SDeleteAllItemsFro = 'Delete all Items from THIS demander?';
  SDemanderIssuesFrom = 'Demander Issues from ';
  STo = ' to ';
  SShowAll = 'Show All';
  SOrdered = 'Ordered';
  SIssued = 'Issued';
  SReceived = 'Received';
  SVariance = 'Variance';
  SStocktake = 'Stocktake';
  SALLPRODUCTS = 'A l l   P r o d u c t s';
  SINSTITUTIONALE = 'I n s t i t u t i o n a l     E D L';
  SPROVINCIALEDL = 'P r o v i n c i a l    E D L';
  SNATIONALEDL = 'N a t i o n a l    E D L';
  SA = 'A = ';
  SDays = ' Days';
  SB = 'B = ';
  SDays1 = ' Days';
  SC = 'C = ';
  SDays2 = ' Days';
  SD = 'D = ';
  SDays3 = ' Days';
  SA1 = 'A = ';
  SDays4 = ' Days';
  SB1 = 'B = ';
  SDays5 = ' Days';
  SC1 = 'C = ';
  SDays6 = ' Days';
  SD1 = 'D = ';
  SDays7 = ' Days';
  SShowingTransactionSBetween = 'Showing transaction(s) between ';
  STo1 = ' to ';
  SShowAll1 = 'Show All';
  SOrdered1 = 'Ordered';
  SIssued1 = 'Issued';
  SReceived1 = 'Received';
  SVariance1 = 'Variance';
  SStocktake1 = 'Stocktake';
  SALLPRODUCTS1 = 'A l l   P r o d u c t s';
  SINSTITUTIONALE1 = 'I n s t i t u t i o n a l     E D L';
  SPROVINCIALEDL1 = 'P r o v i n c i a l    E D L';
  SNATIONALEDL1 = 'N a t i o n a l    E D L';
  SA2 = 'A = ';
  SDays8 = ' Days';
  SB2 = 'B = ';
  SDays9 = ' Days';
  SC2 = 'C = ';
  SDays10 = ' Days';
  SD2 = 'D = ';
  SDays11 = ' Days';
  SA3 = 'A = ';
  SDays12 = ' Days';
  SB3 = 'B = ';
  SDays13 = ' Days';
  SC3 = 'C = ';
  SDays14 = ' Days';
  SD3 = 'D = ';
  SDays15 = ' Days';
  SShowingTransactionSBetween1 = 'Showing transaction(s) between ';
  STo2 = ' to ';
  SOn = ' [ on ';
  SYouCannotDoAVarianceRightN = 'You cannot do a variance right now. The product has been put on hold.';
  SPleaseMakeSureThatItemIsNo = 'Please make sure that item is not on hold before doing a variance.';
  SDELETEPRODUCT = 'DELETE PRODUCT?';
  SCannotDeleteProduct = 'Cannot Delete Product';
  SValidatingProductsForDispensi = 'Validating Products for Dispensing';
  SAutoLevelingProductStockSigl = 'Auto Leveling Product Stock Sigl Method...';
  SItemsHaveAlreadyBeenIssuedO = 'Items have already been issued or contracts exist.  Make the supplier inactive instead.';
  SDELETESUPPLIER = 'DELETE SUPPLIER?';
  SCannotDeleteSupplier = 'Cannot Delete Supplier ';
  SSUPPLIERS = 'S U P P L I E R S';
  SSUPPLIERSActive = 'S U P P L I E R S  (Active)';
  SSUPPLIERSInactive = 'S U P P L I E R S  (Inactive)';
  SDeleteSupplierContact = 'Delete Supplier Contact?';
  SPosted = 'Posted';
  SLockedByAnotherUser = 'Locked by Another User ';
  SERRORMainDataModuleNotAvai = 'ERROR! Main data module not available';
  SDeleteALLItemsProductsOnThi = 'Delete ALL Items/products on this requisition?';
  SNoProcedureHasBeenCalled = 'No Procedure has been called';
  SERRORRequisitionOrMainData = 'ERROR! Requisition or Main data module not available';
  SBalance = 'Balance';
  SBalanceBeforeTransaction = 'Balance (Before transaction)';
  SRequisitionHasBeenCheckedOut = 'Requisition has been checked out by: ';
  SAreYouSureYouWantToUnlock = 'Are you sure you want to unlock this requisition?';
  SRequisitionHasBeenUnlocked = 'Requisition has been unlocked';
  SPleaseSaveTheUserDetailBefo = 'Please Save the user detail before adding access rights';
  SDeleteSelectedUser = 'Delete selected user?';
  SUserAccessRightsHaveBeenCop = 'User access rights have been copied.';
  SNoPatientAvailable = 'No patient available';
  SDoYouWantToDelet = 'Do you want to delete this prescription?';
  SErrorLoadinPaabIn = 'Error loadin paab interface. Please check your Paab settings.';
  SDoYouWantToCopy = 'Do you want to copy this prescription?';
  SAddingAllAUTHORISE = 'Adding all AUTHORISED products for demander';
  SAddingAllInstituti = 'Adding all Institutional EDL products for demander';
  SAddingAllBackorder = 'Adding all Backorder products for demander';
  SPleaseSelectAnAcc = 'Please select an account first';
  SProductCode_IDRequi = 'ProductCode_ID;Requisition_ID';
  SAddingProductS = 'Adding product(s)';
  SDeletedALLItems = '***Deleted ALL items***';
  SDeletedFromRequis = ' deleted from requisition!';
  SBecauseItHasAlrea = 'because it has already been posted!';
  SCannotDeleteRequis = 'Cannot Delete Requisition';
  SDELETEREQUISITION = 'DELETE REQUISITION?';
  SProductCode_IDRequi2 = 'ProductCode_ID;Requisition_ID';
  SGettingItemsListF = 'Getting items list from server';
  SChangedProductType = 'Changed product type';
  SFrom = 'From ';
  STo3 = ' to ';
  SProductAlreadyExis = 'Product already exists in item list.';
  SBatchHasNotBeenS = 'Batch has not been selected. Please select one for use.';
  SOverBy = ' Over By(';
  SYouMayNotIssueMo = 'You may not issue more than you are authorised to!';
  SOverBy1 = ' Over By(';
  SAdministratorOverri = 'Administrator override on authorised stock issue!';
  SRDMFile = 'RDM file ';
  SHasBeenCreatedSu = ' has been created successfully';
  SIssue = 'Issue (';
  SRequest = 'Request (';
  SThisProductHasBee = 'This product has been locked for issuing';
  SCannotIssueMoreTh = 'Cannot issue more then avaliable stock';


implementation

end.
